// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkN5LIv_3gc3k9aKTs6lpCTYOm8UOmt4',
    appId: '1:343141292352:web:346b9957887a5ded1c42a5',
    messagingSenderId: '343141292352',
    projectId: 'kejime-dart',
    authDomain: 'kejime-dart.firebaseapp.com',
    storageBucket: 'kejime-dart.firebasestorage.app',
    measurementId: 'G-D1EXQLZ2TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPB7bhM68w2SlwmrgnHvgbjM91Ls3DlyU',
    appId: '1:343141292352:android:aa3a71f63d531c0f1c42a5',
    messagingSenderId: '343141292352',
    projectId: 'kejime-dart',
    storageBucket: 'kejime-dart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIAznVv7c_-IXOamIYpwje4YbDaaI5yI',
    appId: '1:343141292352:ios:9a129eed6d533a991c42a5',
    messagingSenderId: '343141292352',
    projectId: 'kejime-dart',
    storageBucket: 'kejime-dart.firebasestorage.app',
    iosBundleId: 'com.example.kejime2024',
  );

}